// stories-data.ts
// 베풂의 교만 이야기 · Arrogant Generosity
// 38편 · 6부 — Final arrangement

export type Lang = 'ko' | 'en'

export interface Story {
  id: number
  part: number
  titleKo: string
  titleEn: string
  subtitleKo: string
  subtitleEn: string
  digestKo: string
  digestEn: string
  driveKo: string
  driveEn: string
  driveFileKo: string
  driveFileEn: string
  drivePptKo?: string
  slug?: string
  audiences?: string[]
  tags?: string[]
}

const d = (id: string) => `https://docs.google.com/document/d/${id}/edit`
const p = (id: string) => `https://docs.google.com/presentation/d/${id}/edit`

export const stories: Story[] = [

  // ─── 1부 · Part 1 — 받고, 자라고, 베풀고 · Receiving, Growing, Giving ───

  {
    id: 1,
    part: 1,
    titleKo: '베풂의 교만',
    titleEn: 'Arrogant Generosity',
    subtitleKo: '주는 것도 교만이 될 수 있다',
    subtitleEn: 'On giving, receiving, and the pride we don\'t see',
    digestKo: '<!-- TODO: 베풂의 교만 카드 텍스트 -->',
    digestEn: '<!-- TODO: Arrogant Generosity card text -->',
    driveKo: d('1UAjceY0'),
    driveEn: d('1rUMNlz4'),
    driveFileKo: d('1UAjceY0'),
    driveFileEn: d('1rUMNlz4'),
  },
  {
    id: 2,
    part: 1,
    titleKo: 'Hamburger and Fries',
    titleEn: 'Hamburger and Fries',
    subtitleKo: '모르면서 모른다고 하지 못할 때',
    subtitleEn: 'On not knowing what you don\'t know — and ordering anyway',
    digestKo: '<!-- TODO: Hamburger and Fries 카드 텍스트 (KO) -->',
    digestEn: '<!-- TODO: Hamburger and Fries card text (EN) -->',
    driveKo: d('1xy-uc0-'),
    driveEn: d('17UZMqsK'),
    driveFileKo: d('1xy-uc0-'),
    driveFileEn: d('17UZMqsK'),
  },
  {
    id: 3,
    part: 1,
    titleKo: 'May I Help YOU?',
    titleEn: 'May I Help YOU?',
    subtitleKo: '유효함과 효율성 사이에서',
    subtitleEn: 'Between effectiveness and efficiency',
    digestKo: '<!-- TODO: May I Help YOU? 카드 텍스트 (KO) -->',
    digestEn: '<!-- TODO: May I Help YOU? card text (EN) -->',
    driveKo: d('163fHpkx'),
    driveEn: d('15V93Xvz'),
    driveFileKo: d('163fHpkx'),
    driveFileEn: d('15V93Xvz'),
  },
  {
    id: 4,
    part: 1,
    titleKo: '반응하기 vs 응답하기',
    titleEn: 'React and Respond',
    subtitleKo: '후회하는 것과 후회하지 않는 것',
    subtitleEn: 'What we regret — and what we don\'t',
    digestKo: '<!-- TODO: 반응하기 vs 응답하기 카드 텍스트 -->',
    digestEn: '<!-- TODO: React and Respond card text -->',
    driveKo: d('1hw1jUWN'),
    driveEn: d('1WO9H9vQ'),
    driveFileKo: d('1hw1jUWN'),
    driveFileEn: d('1WO9H9vQ'),
  },
  {
    id: 5,
    part: 1,
    titleKo: '기선, 범선, 부선',
    titleEn: 'Motor Boats, Sail Boats, Barges',
    subtitleKo: '나는 어떤 배인가',
    subtitleEn: 'On the direction of a life',
    digestKo: '<!-- TODO: 기선, 범선, 부선 카드 텍스트 -->',
    digestEn: '<!-- TODO: Motor Boats, Sail Boats, Barges card text -->',
    driveKo: d('1P80WP-f'),
    driveEn: d('17QD51DG'),
    driveFileKo: d('1P80WP-f'),
    driveFileEn: d('17QD51DG'),
  },

  // ─── 2부 · Part 2 — 이웃으로 산다는 것 · On Living as a Neighbor ───

  {
    id: 6,
    part: 2,
    titleKo: '이웃은 지리적 용어가 아닙니다',
    titleEn: 'Neighbor Is Not a Geographical Term',
    subtitleKo: '등잔 밑이 어두웠네',
    subtitleEn: 'The lamp that doesn\'t shine on its own base',
    digestKo: '<!-- TODO: 이웃은 지리적 용어가 아닙니다 카드 텍스트 -->',
    digestEn: '<!-- TODO: Neighbor Is Not a Geographical Term card text -->',
    driveKo: d('1LcaL3rX'),
    driveEn: d('1hd3jOkh'),
    driveFileKo: d('1LcaL3rX'),
    driveFileEn: d('1hd3jOkh'),
  },
  {
    id: 7,
    part: 2,
    titleKo: '길에서 벗어나 모자를 기울이기',
    titleEn: 'Stepping Aside and Tipping the Hat',
    subtitleKo: '작은 몸짓, 그 엄청난 결과',
    subtitleEn: 'On small gestures and their enormous consequences',
    digestKo: '<!-- TODO: 길에서 벗어나 모자를 기울이기 카드 텍스트 -->',
    digestEn: '<!-- TODO: Stepping Aside and Tipping the Hat card text -->',
    driveKo: d('1Kn_IMxN'),
    driveEn: d('1wLLS0sS'),
    driveFileKo: d('1Kn_IMxN'),
    driveFileEn: d('1wLLS0sS'),
  },
  {
    id: 8,
    part: 2,
    titleKo: '아보카도 나무',
    titleEn: 'The Avocado Tree',
    subtitleKo: '구조, 공정함, 그리고 시선',
    subtitleEn: 'On structure, fairness, and the way we see',
    digestKo: '<!-- TODO: 아보카도 나무 카드 텍스트 -->',
    digestEn: '<!-- TODO: The Avocado Tree card text -->',
    driveKo: d('1oa2_tCl'),
    driveEn: d('1IMhtJVB'),
    driveFileKo: d('1oa2_tCl'),
    driveFileEn: d('1IMhtJVB'),
  },
  {
    id: 9,
    part: 2,
    titleKo: '겸손과 신뢰로 가르치다',
    titleEn: 'Teaching with Humility and Trust',
    subtitleKo: '칼론지의 소원이 드러낸 것',
    subtitleEn: 'On the door thirty years of labor left unopened',
    digestKo: '<!-- TODO: 겸손과 신뢰로 가르치다 카드 텍스트 -->',
    digestEn: '<!-- TODO: Teaching with Humility and Trust card text -->',
    driveKo: d('15skZ513'),
    driveEn: d('1lEmZ_B3'),
    driveFileKo: d('15skZ513'),
    driveFileEn: d('1lEmZ_B3'),
  },
  {
    id: 10,
    part: 2,
    titleKo: '겸손의 힘',
    titleEn: 'The Power of Humility',
    subtitleKo: '약함이 진정한 변화의 조건',
    subtitleEn: 'On weakness, witness, and the questions we don\'t expect to answer',
    digestKo: '<!-- TODO: 겸손의 힘 카드 텍스트 -->',
    digestEn: '<!-- TODO: The Power of Humility card text -->',
    driveKo: d('1dIXQV8W'),
    driveEn: d('1g-yYBB1'),
    driveFileKo: d('1dIXQV8W'),
    driveFileEn: d('1g-yYBB1'),
  },
  {
    id: 11,
    part: 2,
    titleKo: '이웃에게서 배우는 선교사',
    titleEn: 'A Missionary Learning from Neighbors',
    subtitleKo: '대사 한 마디 없는 역이 완성한 이야기',
    subtitleEn: 'On the character with no lines — and the one who saw him first',
    digestKo: '<!-- TODO: 이웃에게서 배우는 선교사 카드 텍스트 -->',
    digestEn: '<!-- TODO: A Missionary Learning from Neighbors card text -->',
    driveKo: d('1jUhINK-'),
    driveEn: d('10roRzQh'),
    driveFileKo: d('1jUhINK-'),
    driveFileEn: d('10roRzQh'),
    drivePptKo: p('1ShrpJjd'),
  },
  {
    id: 12,
    part: 2,
    titleKo: '언어 배우기',
    titleEn: 'Learning a Language',
    subtitleKo: '발언하지 못하는 이들의 고난을 이해하고 공유하기',
    subtitleEn: 'On voicelessness, power, and what broken Nepali can do',
    digestKo: '<!-- TODO: 언어 배우기 카드 텍스트 -->',
    digestEn: '<!-- TODO: Learning a Language card text -->',
    driveKo: d('1DEojH3Z'),
    driveEn: d('1GRKjFfM'),
    driveFileKo: d('1DEojH3Z'),
    driveFileEn: d('1GRKjFfM'),
  },
  {
    id: 13,
    part: 2,
    titleKo: '몇 명이나 전도했어요?',
    titleEn: 'How Many People Have You Converted?',
    subtitleKo: 'Amodou의 십자가에 대하여',
    subtitleEn: 'On Amodou\'s cross — and the power of a relationship with no result yet',
    digestKo: '<!-- TODO: 몇 명이나 전도했어요? 카드 텍스트 -->',
    digestEn: '<!-- TODO: How Many People Have You Converted? card text -->',
    driveKo: d('1vbVdRKG'),
    driveEn: d('1PenqwDh'),
    driveFileKo: d('1vbVdRKG'),
    driveFileEn: d('1PenqwDh'),
    drivePptKo: p('1ShrpJjd'),
  },
  {
    id: 14,
    part: 2,
    titleKo: '콩고 시골교회 어른',
    titleEn: 'An Elderly Man from a Rural Church in Congo',
    subtitleKo: '하나님이 아직 우리를 기억하신다',
    subtitleEn: 'God still remembers us',
    digestKo: '<!-- TODO: 콩고 시골교회 어른 카드 텍스트 -->',
    digestEn: '<!-- TODO: An Elderly Man from a Rural Church in Congo card text -->',
    driveKo: d('1E3GWzqP'),
    driveEn: d('1sXzAyDI'),
    driveFileKo: d('1E3GWzqP'),
    driveFileEn: d('1sXzAyDI'),
    drivePptKo: p('1fhFd4q3'),
  },

  // ─── 3부 · Part 3 — 배우며 실수하며 · Learning Through Mistakes ───

  {
    id: 15,
    part: 3,
    titleKo: '섣부른 해결책',
    titleEn: 'Hasty Solutions',
    subtitleKo: '이해하지 못하면서 해결하려 할 때',
    subtitleEn: 'On the assumptions we carry — and the silences that teach us',
    digestKo: '<!-- TODO: 섣부른 해결책 카드 텍스트 -->',
    digestEn: '<!-- TODO: Hasty Solutions card text -->',
    driveKo: d('100qNMYv'),
    driveEn: d('1BstoWqX'),
    driveFileKo: d('100qNMYv'),
    driveFileEn: d('1BstoWqX'),
    drivePptKo: p('1Aq0-QyF'),
  },
  {
    id: 16,
    part: 3,
    titleKo: '다코로의 선물',
    titleEn: 'Dakoro\'s Gift',
    subtitleKo: '규칙, 생명, 그리고 공동체가 가진 지혜',
    subtitleEn: 'On rules, lives, and the wisdom a community already holds',
    digestKo: '<!-- TODO: 다코로의 선물 카드 텍스트 -->',
    digestEn: '<!-- TODO: Dakoro\'s Gift card text -->',
    driveKo: d('1jZuv9ad'),
    driveEn: d('1HDItjzd'),
    driveFileKo: d('1jZuv9ad'),
    driveFileEn: d('1HDItjzd'),
    drivePptKo: p('1fhFd4q3'),
  },
  {
    id: 17,
    part: 3,
    titleKo: '내가 가서',
    titleEn: 'As I Go',
    subtitleKo: '"미개인"을 하나님의 자녀로 — 이 과오는 어디서 오는가',
    subtitleEn: 'On the assumption of arrival — and the discipline of staying on the way',
    digestKo: '<!-- TODO: 내가 가서 카드 텍스트 -->',
    digestEn: '<!-- TODO: As I Go card text -->',
    driveKo: d('15HZQO59'),
    driveEn: d('1QiP6a9H'),
    driveFileKo: d('15HZQO59'),
    driveFileEn: d('1QiP6a9H'),
  },
  {
    id: 18,
    part: 3,
    titleKo: '열심 있는 사람들의 병',
    titleEn: 'The Disease of the Zealous',
    subtitleKo: '열심과 소명을 혼동하는 위험',
    subtitleEn: 'On mistaking passion for calling — and serving for leading',
    digestKo: '<!-- TODO: 열심 있는 사람들의 병 카드 텍스트 -->',
    digestEn: '<!-- TODO: The Disease of the Zealous card text -->',
    driveKo: d('1GFvJc6d'),
    driveEn: d('1OT0f54I'),
    driveFileKo: d('1GFvJc6d'),
    driveFileEn: d('1OT0f54I'),
  },
  {
    id: 19,
    part: 3,
    titleKo: '재난',
    titleEn: 'Disaster',
    subtitleKo: 'TV 카메라가 떠난 후부터 시작되는 것',
    subtitleEn: 'What begins after the TV cameras leave',
    digestKo: '<!-- TODO: 재난 카드 텍스트 -->',
    digestEn: '<!-- TODO: Disaster card text -->',
    driveKo: d('10AaOMbp'),
    driveEn: d('1p0b-ap4'),
    driveFileKo: d('10AaOMbp'),
    driveFileEn: d('1p0b-ap4'),
  },
  {
    id: 20,
    part: 3,
    titleKo: '내 아들에게 말하는 중이다',
    titleEn: 'I Am Speaking to My Son',
    subtitleKo: '감당할 수 없을 때 — 한 발자국 물러나는 것에 대하여',
    subtitleEn: 'On limits, burnout, and the discipline of stepping back',
    digestKo: '<!-- TODO: 내 아들에게 말하는 중이다 카드 텍스트 -->',
    digestEn: '<!-- TODO: I Am Speaking to My Son card text -->',
    driveKo: d('1y9bcqVX'),
    driveEn: d('1eShMcCB'),
    driveFileKo: d('1y9bcqVX'),
    driveFileEn: d('1eShMcCB'),
  },

  // ─── 4부 · Part 4 — 편견에 갇힌 우리 · Caught Inside Our Own Frames ───

  {
    id: 21,
    part: 4,
    titleKo: '요한이',
    titleEn: 'Yo-han',
    subtitleKo: '다문화 가정 · 첫인상 · 이름',
    subtitleEn: 'Multicultural Family',
    digestKo: '<!-- TODO: 요한이 카드 텍스트 -->',
    digestEn: '<!-- TODO: Yo-han card text -->',
    driveKo: d('1N58qRs1'),
    driveEn: d('1pQ0UtuZ'),
    driveFileKo: d('1N58qRs1'),
    driveFileEn: d('1pQ0UtuZ'),
  },
  {
    id: 22,
    part: 4,
    titleKo: '오늘의 성소수자 차별',
    titleEn: 'Today\'s Discrimination Against Sexual Minorities',
    subtitleKo: '행동(Doing)이 아니라 존재(Being) 때문에 받는 대우에 대하여',
    subtitleEn: 'On being treated not for what you do, but for who you are',
    digestKo: '<!-- TODO: 오늘의 성소수자 차별 카드 텍스트 -->',
    digestEn: '<!-- TODO: Today\'s Discrimination Against Sexual Minorities card text -->',
    driveKo: d('1mwW2ZGA'),
    driveEn: d('1QFBtoym'),
    driveFileKo: d('1mwW2ZGA'),
    driveFileEn: d('1QFBtoym'),
  },
  {
    id: 23,
    part: 4,
    titleKo: '양과 질, 그리고 숨길 수 없는 진실',
    titleEn: 'Quantity, Quality, and the Truth That Cannot Be Hidden',
    subtitleKo: 'Yes and No',
    subtitleEn: 'Yes and No',
    digestKo: '<!-- TODO: 양과 질 카드 텍스트 -->',
    digestEn: '<!-- TODO: Quantity, Quality card text -->',
    driveKo: d('14H10Q2f'),
    driveEn: d('1fJV29t6'),
    driveFileKo: d('14H10Q2f'),
    driveFileEn: d('1fJV29t6'),
    drivePptKo: p('1mJLohny'),
  },
  {
    id: 24,
    part: 4,
    titleKo: '역사적 사실과 진실',
    titleEn: 'Historical Facts and Truth',
    subtitleKo: '부분적 진실, 전체 진실, 그리고 다른 목소리를 들을 용기',
    subtitleEn: 'On partial truths, whole truth, and the courage to listen',
    digestKo: '<!-- TODO: 역사적 사실과 진실 카드 텍스트 -->',
    digestEn: '<!-- TODO: Historical Facts and Truth card text -->',
    driveKo: d('1Z-LzHPJ'),
    driveEn: d('1DzOJ7Wi'),
    driveFileKo: d('1Z-LzHPJ'),
    driveFileEn: d('1DzOJ7Wi'),
    drivePptKo: p('1C5Q7uwR'),
  },
  {
    id: 25,
    part: 4,
    titleKo: '모르는 것 없어요',
    titleEn: 'There\'s Nothing We Don\'t Know',
    subtitleKo: '모르는 것을 모르는 것이 가장 위험한 모름이다',
    subtitleEn: 'On the most dangerous kind of not-knowing',
    digestKo: '<!-- TODO: 모르는 것 없어요 카드 텍스트 -->',
    digestEn: '<!-- TODO: There\'s Nothing We Don\'t Know card text -->',
    driveKo: d('1TX-BT1P'),
    driveEn: d('1-dkaITP'),
    driveFileKo: d('1TX-BT1P'),
    driveFileEn: d('1-dkaITP'),
  },
  {
    id: 26,
    part: 4,
    titleKo: 'N차 방정식',
    titleEn: 'Nth-Degree Equation',
    subtitleKo: '답은 하나가 아닐 수 있습니다',
    subtitleEn: 'Life has more than one answer',
    digestKo: '<!-- TODO: N차 방정식 카드 텍스트 -->',
    digestEn: '<!-- TODO: Nth-Degree Equation card text -->',
    driveKo: d('177Ze5ti'),
    driveEn: d('1jK_ltel'),
    driveFileKo: d('177Ze5ti'),
    driveFileEn: d('1jK_ltel'),
  },
  {
    id: 27,
    part: 4,
    titleKo: '나 하나를 바쳐서',
    titleEn: 'Sacrificing Myself',
    subtitleKo: '이 사건이 사람들의 기억에서 사라지지 않는 불씨가 된다면',
    subtitleEn: 'On a student willing to be beaten for a spark',
    digestKo: '<!-- TODO: 나 하나를 바쳐서 카드 텍스트 -->',
    digestEn: '<!-- TODO: Sacrificing Myself card text -->',
    driveKo: d('1HCEi5ZV'),
    driveEn: d('1Inc42aR'),
    driveFileKo: d('1HCEi5ZV'),
    driveFileEn: d('1Inc42aR'),
  },

  // ─── 5부 · Part 5 — 정의와 치유 · Justice and Healing ───

  {
    id: 28,
    part: 5,
    titleKo: '정의와 자비',
    titleEn: 'Justice and Mercy',
    subtitleKo: '법을 지키는 것과 자비를 베푸는 것은 양립할 수 있는가',
    subtitleEn: 'On law, compassion, and the doors others opened for us',
    digestKo: '<!-- TODO: 정의와 자비 카드 텍스트 -->',
    digestEn: '<!-- TODO: Justice and Mercy card text -->',
    driveKo: d('1VfsHd8j'),
    driveEn: d('1HrT9tGb'),
    driveFileKo: d('1VfsHd8j'),
    driveFileEn: d('1HrT9tGb'),
  },
  {
    id: 29,
    part: 5,
    titleKo: '탁실라 기독병원',
    titleEn: 'Taxila Christian Hospital',
    subtitleKo: '악을 선으로 갚는 성숙함에 대하여',
    subtitleEn: 'On repaying evil with good',
    digestKo: '<!-- TODO: 탁실라 기독병원 카드 텍스트 -->',
    digestEn: '<!-- TODO: Taxila Christian Hospital card text -->',
    driveKo: d('15YEt7s-'),
    driveEn: d('1npUkWWj'),
    driveFileKo: d('15YEt7s-'),
    driveFileEn: d('1npUkWWj'),
    drivePptKo: p('1yZQ8P9i'),
  },
  {
    id: 30,
    part: 5,
    titleKo: '전인치유',
    titleEn: 'Whole Person Healing',
    subtitleKo: '한 생명의 보호로부터 역 한 정거장까지',
    subtitleEn: 'From protecting one life — to one train stop away',
    digestKo: '<!-- TODO: 전인치유 카드 텍스트 -->',
    digestEn: '<!-- TODO: Whole Person Healing card text -->',
    driveKo: d('14_M9bWS'),
    driveEn: d('122ePSzS'),
    driveFileKo: d('14_M9bWS'),
    driveFileEn: d('122ePSzS'),
    drivePptKo: p('1yZQ8P9i'),
  },
  {
    id: 31,
    part: 5,
    titleKo: 'HIV/AIDS — 누구의 책임인가?',
    titleEn: 'Beyond the Enemy',
    subtitleKo: '불치병 너머의 사람을 본 여인들',
    subtitleEn: 'On seeing the person inside the crisis',
    digestKo: '<!-- TODO: HIV/AIDS 카드 텍스트 -->',
    digestEn: '<!-- TODO: Beyond the Enemy card text -->',
    driveKo: d('1xHibnha'),
    driveEn: d('100FxFnN'),
    driveFileKo: d('1xHibnha'),
    driveFileEn: d('100FxFnN'),
    drivePptKo: p('1mDUazuA'),
  },
  {
    id: 32,
    part: 5,
    titleKo: '사회정의',
    titleEn: 'Social Justice',
    subtitleKo: '설탕 한 포대 — 거시와 미시, 그리고 지금 내 앞의 이 사람',
    subtitleEn: 'On the macro and the micro — and the sugar sack in between',
    digestKo: '<!-- TODO: 사회정의 카드 텍스트 -->',
    digestEn: '<!-- TODO: Social Justice card text -->',
    driveKo: d('1GOVCdeZ'),
    driveEn: d('1CxLhr86'),
    driveFileKo: d('1GOVCdeZ'),
    driveFileEn: d('1CxLhr86'),
  },

  // ─── 6부 · Part 6 — 풍성한 삶이란? · What Is a Full Life? ───

  {
    id: 33,
    part: 6,
    titleKo: '선교사의 은퇴, 은퇴 후 선교',
    titleEn: 'Pursuing the Best',
    subtitleKo: '새로운 환경에서의 이웃됨은 반복된다',
    subtitleEn: 'On missionary stages, retirement stages, and the folding table',
    digestKo: '<!-- TODO: 선교사의 은퇴 카드 텍스트 -->',
    digestEn: '<!-- TODO: Pursuing the Best card text -->',
    driveKo: d('1jHxka8h'),
    driveEn: d('1QkWh67O'),
    driveFileKo: d('1jHxka8h'),
    driveFileEn: d('1QkWh67O'),
  },
  {
    id: 34,
    part: 6,
    titleKo: '극대화와 충분함',
    titleEn: 'God\'s Grace Is Sufficient',
    subtitleKo: '40% 작은 삶이 더 풍성했다',
    subtitleEn: 'On what a life of less taught about enough',
    digestKo: '<!-- TODO: 극대화와 충분함 카드 텍스트 -->',
    digestEn: '<!-- TODO: God\'s Grace Is Sufficient card text -->',
    driveKo: d('14XCkAg9'),
    driveEn: d('1nD6uWXy'),
    driveFileKo: d('14XCkAg9'),
    driveFileEn: d('1nD6uWXy'),
  },
  {
    id: 35,
    part: 6,
    titleKo: '한 사람의 죽음이 무슨 차이를 만드는가',
    titleEn: 'What Difference Does One Person\'s Death Make?',
    subtitleKo: '유산, 겸손, 그리고 세금 신고서',
    subtitleEn: 'On legacy, humility, and tax returns',
    digestKo: '<!-- TODO: 한 사람의 죽음이 카드 텍스트 -->',
    digestEn: '<!-- TODO: What Difference Does One Person\'s Death Make? card text -->',
    driveKo: d('1gAwREYZ'),
    driveEn: d('1tqOs6pV'),
    driveFileKo: d('1gAwREYZ'),
    driveFileEn: d('1tqOs6pV'),
  },
  {
    id: 36,
    part: 6,
    titleKo: '독자들과 같이 만드는 이야기',
    titleEn: 'A Story Made Together with Readers',
    subtitleKo: '예약된 자리',
    subtitleEn: 'A reserved seat',
    digestKo: '<!-- TODO: 독자들과 같이 만드는 이야기 카드 텍스트 -->',
    digestEn: '<!-- TODO: A Story Made Together with Readers card text -->',
    driveKo: d('18VlAlUZ'),
    driveEn: d('1U45hWW2'),
    driveFileKo: d('18VlAlUZ'),
    driveFileEn: d('1U45hWW2'),
  },
  {
    id: 37,
    part: 6,
    titleKo: '집 동네에서 나의 선교지를 찾다',
    titleEn: 'Finding My Mission Field at Home',
    subtitleKo: '새로운 환경마다 이웃됨은 처음부터 다시 시작됩니다',
    subtitleEn: 'The work of neighboring never truly ends',
    digestKo: '<!-- TODO: 집 동네에서 나의 선교지를 찾다 카드 텍스트 -->',
    digestEn: '<!-- TODO: Finding My Mission Field at Home card text -->',
    driveKo: d('1Dk6qJZC'),
    driveEn: d('1u8rpdC5'),
    driveFileKo: d('1Dk6qJZC'),
    driveFileEn: d('1u8rpdC5'),
  },
  {
    id: 38,
    part: 6,
    titleKo: '작은 미소',
    titleEn: 'A Small Smile',
    subtitleKo: '이름이 아니라 미소를 남기고 싶다',
    subtitleEn: 'I want to leave a smile, not a name',
    digestKo: '<!-- TODO: 작은 미소 카드 텍스트 -->',
    digestEn: '<!-- TODO: A Small Smile card text -->',
    driveKo: d('1ppL6khn'),
    driveEn: d('1DJ1RivJ'),
    driveFileKo: d('1ppL6khn'),
    driveFileEn: d('1DJ1RivJ'),
  },
]

// Part labels
export const partLabels: Record<number, { ko: string; en: string }> = {
  1: { ko: '1부 — 받고, 자라고, 베풀고', en: 'Part 1 — Receiving, Growing, Giving' },
  2: { ko: '2부 — 이웃으로 산다는 것', en: 'Part 2 — On Living as a Neighbor' },
  3: { ko: '3부 — 배우며 실수하며', en: 'Part 3 — Learning Through Mistakes' },
  4: { ko: '4부 — 편견에 갇힌 우리', en: 'Part 4 — Caught Inside Our Own Frames' },
  5: { ko: '5부 — 정의와 치유', en: 'Part 5 — Justice and Healing' },
  6: { ko: '6부 — 풍성한 삶이란?', en: 'Part 6 — What Is a Full Life?' },
}

// Read Me First links
export const readMeFirst = {
  ko: 'https://docs.google.com/document/d/1nqi3Ms9JqXTuMPLAK7QzkmpLNTg-sS3V/edit',
  en: 'https://docs.google.com/document/d/1bhCEx6M7Y9_9Uiql62jpugu_B0JiM2SP/edit',
}

